/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import * as THREE from "three";
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../longboard.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.Deka}
        geometry={nodes.Bolt_01014.geometry}
        position={[1.99, 1.26, -42.27]}
        rotation={[-Math.PI / 2, 0, 0.99]}>
        <mesh
          material={materials.Deka}
          geometry={nodes.BoltLow_01014.geometry}
          position={[0, 0, 0]}
          rotation={[0, 0, 0.99]}
        />
      </mesh>
      <mesh
        material={materials.Deka}
        geometry={nodes.Wheel009.geometry}
        position={[-10.28, -5.02, -38.92]}
        rotation={[-0.78, 0, 0]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Bolt_01012.geometry}
        position={[-2.02, 1.26, -36.96]}
        rotation={[-Math.PI / 2, 0, 0.55]}>
        <mesh
          material={materials.Deka}
          geometry={nodes.BoltLow_01012.geometry}
          position={[0, 0, 0]}
          rotation={[0, 0, 0.55]}
        />
      </mesh>
      <mesh
        material={materials.Deka}
        geometry={nodes.Bolt_01018.geometry}
        position={[-2, 1.26, 42.42]}
        rotation={[-Math.PI / 2, 0, -1.88]}
        scale={[1, 1, 1]}>
        <mesh
          material={materials.Deka}
          geometry={nodes.BoltLow_01018.geometry}
          position={[0, 0, 0]}
          rotation={[0, 0, 0.99]}
        />
      </mesh>
      <mesh
        material={materials.Deka}
        geometry={nodes.Podveska005.geometry}
        position={[0, -1.06, -43.24]}
        rotation={[-2.4, 0, 0]}>
        <mesh material={materials.Deka} geometry={nodes.Zhelezka005.geometry} position={[0, 0, -3.6]} />
        <mesh material={materials.Deka} geometry={nodes.BoltBig005.geometry} position={[0, 0, -3.6]} />
        <mesh material={materials.Deka} geometry={nodes.GaikaBig005.geometry} position={[0, 0, -3.6]} />
        <mesh material={materials.Deka} geometry={nodes.RezinkaBig005.geometry} position={[0, 0, -3.6]} />
      </mesh>
      <mesh
        material={materials.Deka}
        geometry={nodes.GaikaWheel009.geometry}
        position={[11, -5.02, -38.92]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Bolt_01011.geometry}
        position={[-2.11, 1.26, -42.25]}
        rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Deka} geometry={nodes.BoltLow_01011.geometry} />
      </mesh>
      <mesh
        material={materials.Deka}
        geometry={nodes.Bolt_01013.geometry}
        position={[2.03, 1.26, -36.96]}
        rotation={[-Math.PI / 2, 0, 0.99]}>
        <mesh material={materials.Deka} geometry={nodes.BoltLow_01013.geometry} rotation={[0, 0, 0.99]} />
      </mesh>
      <mesh material={new THREE.MeshStandardMaterial({color: 0xff0000})} geometry={nodes.Deka004.geometry} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh
        material={materials.Deka}
        geometry={nodes.GaikaWheel010.geometry}
        position={[10.98, -5.02, 39.07]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[1, 1, 1]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Podveska006.geometry}
        position={[-0.01, -1.06, 43.38]}
        rotation={[-0.74, 0, -Math.PI]}>
        <mesh
          material={materials.Deka}
          geometry={nodes.GaikaBig006.geometry}
          position={[0, 0, -3.6]}
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials.Deka}
          geometry={nodes.Zhelezka006.geometry}
          position={[0, 0, -3.6]}
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials.Deka}
          geometry={nodes.RezinkaBig006.geometry}
          position={[0, 0, -3.6]}
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials.Deka}
          geometry={nodes.BoltBig006.geometry}
          position={[0, 0, -3.6]}
          rotation={[0, 0, 0]}
        />
      </mesh>
      <mesh
        material={materials.Deka}
        geometry={nodes.GaikaWheel011.geometry}
        position={[-11.01, -5.02, 39.07]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[1, 1, 1]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Amort_krep006.geometry}
        position={[-0.01, 1.06, 44.35]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[1, 1, 1]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Bolt_01016.geometry}
        position={[2.01, 1.26, 37.11]}
        rotation={[-Math.PI / 2, 0, -2.44]}
        scale={[1, 1, 1]}>
        <mesh
          material={materials.Deka}
          geometry={nodes.BoltLow_01016.geometry}
          position={[0, 0, 0]}
          rotation={[0, 0, 0.55]}
        />
      </mesh>
      <mesh
        material={materials.Deka}
        geometry={nodes.Rzinka006.geometry}
        position={[-0.01, -1.06, 43.38]}
        rotation={[-0.74, 0, -Math.PI]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Amort_krep005.geometry}
        position={[0, 1.06, -44.2]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Wheel012.geometry}
        position={[-10.29, -5.02, 39.07]}
        rotation={[-0.02, 0, -Math.PI]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Wheel010.geometry}
        position={[10.28, -5.02, -38.92]}
        rotation={[-2.26, 0, 0]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Rzinka005.geometry}
        position={[0, -1.06, -43.24]}
        rotation={[-2.4, 0, 0]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Bolt_01017.geometry}
        position={[-2.05, 1.26, 37.11]}
        rotation={[-Math.PI / 2, 0, -2.39]}
        scale={[1, 1, 1]}>
        <mesh material={materials.Deka} geometry={nodes.BoltLow_01017.geometry} rotation={[0, 0, 0.99]} />
      </mesh>
      <mesh
        material={materials.Deka}
        geometry={nodes.GaikaWheel008.geometry}
        position={[-11, -5.02, -38.92]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Wheel011.geometry}
        position={[10.27, -5.02, 39.07]}
        rotation={[-2.55, 0, -Math.PI]}
      />
      <mesh
        material={materials.Deka}
        geometry={nodes.Bolt_01015.geometry}
        position={[2.05, 1.26, 42.4]}
        rotation={[-Math.PI / 2, 0, -2.08]}>
        <mesh
          material={materials.Deka}
          geometry={nodes.BoltLow_01015.geometry}
          position={[0, 0, 0]}
          rotation={[0, 0, 1.06]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('../../../longboard.glb')
