/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../FirsrDonut2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['Material.003']}
        geometry={nodes.Donut.geometry}
        position={[0, 0.03, 0]}
        rotation={[0.04, 0, 0]}>
        <mesh material={materials['Material.002']} geometry={nodes.Icing.geometry} />
      </mesh>
      <mesh material={materials['Material.001']} geometry={nodes.Plane.geometry} />
      <mesh material={materials['Material.004']} geometry={nodes.Sprinkle_Sort.geometry} position={[0.18, 0, 0]} />
      <mesh material={materials['Material.004']} geometry={nodes.Sprinkle_Long.geometry} position={[0.19, 0, 0]} />
      <mesh material={materials['Material.004']} geometry={nodes.Sprinkle_Med.geometry} position={[0.19, 0, 0]} />
      <mesh material={materials['Material.004']} geometry={nodes.Sprinkle_Long001.geometry} position={[0.2, 0, 0]} />
      <mesh material={materials['Material.004']} geometry={nodes.Sprinkle_Med002.geometry} position={[0.18, 0, 0]} />
      <mesh material={materials['Material.005']} geometry={nodes.Sphere001.geometry} position={[0.21, 0, 0]} />
    </group>
  )
}

useGLTF.preload('../../..//FirsrDonut2.glb')
